{% set version = "1.2.0" %}

package:
  name: stringcase
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stringcase/stringcase-{{ version }}.tar.gz
  sha256: 48a06980661908efe8d9d34eab2b6c13aefa2163b3ced26972902e3bdfd87008

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - stringcase
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/okunishinishi/python-stringcase
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |-
    Convert string cases between camel case, pascal case, snake case etc...

extra:
  recipe-maintainers:
    - bollwyvl
